Django_02/posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'
urlpatterns = [
    path('', views.index, name='index'),
    path('category/<str:subject>/', views.category, name='category'),
    path('create/', views.create, name='create'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/update/', views.update, name='update'),
]

Django_02/project_two/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('posts/', include('posts.urls')),
]

Django_02/posts/models.py
from django.db import models
from django.forms import ModelForm


class Post(models.Model):
    category_choices = [('개발', '개발'), ('CS', 'CS'), ('신기술', '신기술'),]
    title = models.CharField(max_length=80)
    content = models.TextField(null=False)
    category = models.CharField(max_length=3, choices=category_choices)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

Django_02/posts/forms.py
from django import forms
from .models import Post


class PostForm(forms.ModelForm):
    category_choices = [('개발', '개발'), ('CS', 'CS'), ('신기술', '신기술'),]
    title = forms.CharField(
        label='제목',
        widget=forms.TextInput(
        attrs={
            'class': 'form-control',
            'placeholder': '제목을 입력해주세요.'
        }
        )
    )
    content = forms.CharField(
        label='내용',
        widget=forms.Textarea(
        attrs={
            'class': 'form-control',
            'placeholder': '내용을 입력해주세요.',
            'style': 'height: 10em;',
        }
        )
    )
    category = forms.CharField(
        max_length=3,
        widget=forms.Select(choices=category_choices)
    )
    class Meta:
        model = Post
        fields = ('title', 'content', 'category')

Django_02/posts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from .models import Post
from .forms import PostForm


@login_required
def category(request, subject):
    posts = Post.objects.filter(category=subject)
    context = {
        'posts': posts,
    }
    return render(request, 'posts/index.html', context)


@login_required
def index(request):
    posts = Post.objects.all()
    context = {
        'posts': posts
    }
    return render(request, 'posts/index.html', context)


@login_required
def create(request):
    if request.method == 'POST':
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save()
            return redirect('posts:detail', post.pk)
    else:
        form = PostForm()
    context = {
        'form': form,
    }
    return render(request, 'posts/new.html', context)


@login_required
def detail(request, pk):
    post = Post.objects.get(pk=pk)
    context = {
        'post': post,
    }
    return render(request, 'posts/detail.html', context)


@login_required
def delete(request, pk):
    post = Post.objects.get(pk=pk)
    post.delete()
    return redirect('posts:index')


@login_required
def update(request, pk):
    post = Post.objects.get(pk=pk)
    if request.method == 'POST':
        form = PostForm(request.POST, instance=post)
        if form.is_valid():
            form.save()
            return redirect('posts:detail', post.pk)
    else:
        form = PostForm(instance=post)
    context = {
        'post': post,
        'form': form,
    }
    return render(request, 'posts/edit.html', context)

Django_02/posts/templates/posts/detail.html
{% extends 'base.html' %}
{% block title %} 상세보기 {% endblock title %}
{% block body %}
<div class="container w-50">
  <div class="d-flex align-items-center">
    <h3 class="m-0">{{ post.category }}</h3>
    <h1 class="text-center flex-grow-1">{{ post.title }}</h1>
    <p class="fs-6 text-end m-0 me-3">{{ post.pk }}</p>
  </div>
  <hr class="mt-0 mb-3">
  <div class="mb-3" style="word-wrap: break-word;">
    {{ post.content }}
  </div>
  <div class="d-flex justify-content-between">
    <a href="{% url 'posts:index' %}" class="btn btn-outline-success">뒤로가기</a>
    <div class="d-flex justify-content-between">
      <a href="{% url 'posts:update' post.pk %}" class="btn btn-outline-primary me-3">수정</a>
      <form action="{% url 'posts:delete' post.pk %}" method="POST">
        {% csrf_token %}
        <button type="sumbit" class="btn btn-outline-danger">삭제</button>
      </form>
    </div>
  </div>
</div>
{% endblock body %}

Django_02/posts/templates/posts/edit.html
{% extends 'base.html' %}
{% block title %} 게시글 수정 {% endblock title %}
{% block style %}
.form-floating>.form-control,
.form-floating>.form-control-plaintext {
  padding: 0rem 0.75rem;
}

.form-floating>.form-control,
.form-floating>.form-control-plaintext,
.form-floating>.form-select {
  height: calc(3.5rem + 8px);
  line-height: 2;
}

.form-floating>label {
  padding: 1rem 0.75rem;
}
{% endblock style %}
{% block body %}
<div class="container w-50">
  <h2 class="my-3 text-center">게시글 수정하기</h2>
  <form action="{% url 'posts:update' post.pk %}" method='POST'>
    {% csrf_token %}
    {% include 'error.html' %}
    <div class="form-floating mb-3">
      {{ form.title }}
      <label for="{{ form.title.id_for_label }}">제목</label>
    </div>
    <div class="form-floating mb-3">
      <select class="form-select" id="{{ form.category.id_for_label }}" name="category">
        <option value="개발" {% if post.category == '개발' %}selected{% endif %}>개발</option>
        <option value="CS" {% if post.category == 'CS' %}selected{% endif %}>CS</option>
        <option value="신기술" {% if post.category == '신기술' %}selected{% endif %}>신기술</option>
      </select>
      <label for="{{ form.category.id_for_label }}">분류</label>
    </div>
    <div class="form-floating mb-3">
      {{ form.content }}
      <label for="{{ form.content.id_for_label }}">내용</label>
    </div>
    <div class="d-flex justify-content-between">
        <a href="{% url 'posts:index' %}" class="btn btn-outline-danger">뒤로가기</a>
        <input type="submit" value="수정" class="btn btn-outline-primary">
    </div>
  </form>
</div>
{% endblock body %}

Django_02/posts/templates/posts/index.html
{% extends 'base.html' %}
{% block title %} 메인 {% endblock title %}
{% block body %}
<div class="container m-auto">
  <table class="table table-borderless table-hover">
    <thead>
      <tr class="table-secondary">
        <th scope="col" style="width: 10%;" class="text-center">#</th>
        <th scope="col" style="width: 15%;" class="text-center">분류</th>
        <th scope="col" class="text-center">제목</th>
      </tr>
    </thead>
    <tbody>
      {% for post in posts %}
      <tr>
        <td class="text-center">{{ post.pk }}</td>
        <td class="text-center">{{ post.category }}</td>
        <td class="text-center" onclick="location.href='{% url 'posts:detail' post.pk %}'" style="cursor: pointer;">{{ post.title }}</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
{% endblock body %}

Django_02/posts/templates/posts/new.html
{% extends 'base.html' %}
{% block title %} 글 작성 {% endblock title %}
{% block style %}
.form-floating>.form-control,
.form-floating>.form-control-plaintext {
  padding: 0rem 0.75rem;
}

.form-floating>.form-control,
.form-floating>.form-control-plaintext,
.form-floating>.form-select {
  height: calc(3.5rem + 8px);
  line-height: 2;
}

.form-floating>label {
  padding: 1rem 0.75rem;
}
{% endblock style %}
{% block body %}
<div class="container w-50">
  <h2 class="my-3 text-center">게시글 작성하기</h2>
  <form action="{% url 'posts:create' %}" method='POST'>
    {% csrf_token %}
    {% include 'error.html' %}
    <div class="form-floating mb-3">
      {{ form.title }}
      <label for="{{ form.title.id_for_label }}">제목</label>
    </div>
    <div class="form-floating mb-3">
      <select class="form-select" id="{{ form.category.id_for_label }}" name="category">
        <option value="" disabled>카테고리 선택</option>
        <option value="개발">개발</option>
        <option value="CS">CS</option>
        <option value="신기술">신기술</option>
      </select>
      <label for="{{ form.category.id_for_label }}">분류</label>
    </div>
    <div class="form-floating mb-3">
      {{ form.content }}
      <label for="{{ form.content.id_for_label }}">내용</label>
    </div>
    <div class="d-flex justify-content-between">
        <a href="{% url 'posts:index' %}" class="btn btn-outline-danger">뒤로가기</a>
        <input type="submit" value="업로드" class="btn btn-outline-primary">
    </div>
  </form>
</div>
{% endblock body %}