Django_01/accountbooks/urls.py
from django.urls import path
from . import views

app_name = 'accountbooks'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:pk>/', views.detail, name='detail'),
    path('new/', views.new, name='new'),
    path('create/', views.create, name='create'),
    path('<int:pk>/edit/', views.edit, name='edit'),
    path('<int:pk>/update/', views.update, name='update'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/copy/', views.copy, name='copy'),
]

Django_01/project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account-books/', include('accountbooks.urls') )
]

Django_01/accountbooks/models.py
from django.db import models

class AccountBook(models.Model):
    note = models.CharField(max_length=80)
    description = models.TextField(null=True)
    category = models.CharField(max_length=20)
    amount = models.IntegerField(default=0)
    date = models.DateField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

Django_01/accountbooks/views.py
from django.shortcuts import render, redirect
from .models import AccountBook


def index(request):
    accountbooks = AccountBook.objects.all()
    context = {
        'accountbooks': accountbooks,
    }

    return render(request, 'accountbooks/index.html', context)


def detail(request, pk):
    accountbook = AccountBook.objects.get(pk=pk)
    context = {
        'accountbook': accountbook,
    }
    return render(request, 'accountbooks/detail.html', context)


def new(request):
    return render(request, 'accountbooks/new.html')


def create(request):
    note = request.POST.get('note')
    description = request.POST.get('description')
    category = request.POST.get('category')
    amount = request.POST.get('amount')
    date = request.POST.get('date')

    accountbook = AccountBook.objects.create(note = note, description = description, category = category, amount = amount, date = date)

    return redirect('accountbooks:detail', accountbook.pk)


def edit(request, pk):
    accountbook = AccountBook.objects.get(pk=pk)
    context = {
        'accountbook': accountbook,
    }
    return render(request, 'accountbooks/edit.html', context)


def update(request, pk):
    accountbook = AccountBook.objects.get(pk=pk)
    accountbook.note = request.POST.get('note')
    accountbook.description = request.POST.get('description')
    accountbook.category = request.POST.get('category')
    accountbook.amount = request.POST.get('amount')
    accountbook.date = request.POST.get('date')

    accountbook.save()

    return redirect('accountbooks:detail', accountbook.pk)


def delete(request, pk):
    accountbook = AccountBook.objects.get(pk=pk)
    accountbook.delete()
    return redirect('accountbooks:index')


def copy(request, pk):
    accountbook = AccountBook.objects.get(pk=pk)
    
    accountbook.pk = None
    accountbook.save()
    return redirect('accountbooks:index')

Django_01/accountbooks/templates/accountbooks/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>가계부</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-aFq/bzH65dt+w6FI2ooMVUpc+21e0SRygnTpmBvdBgSdnuTN7QbdgL+OapgHtvPp" crossorigin="anonymous">
    <style>
      @import url("https://cdn.jsdelivr.net/gh/orioncactus/pretendard@v1.3.6/dist/web/variable/pretendardvariable.css");

      * { font-family: 'Pretendard Variable'; }

      {% block style %}
      {% endblock style %}
    </style>
  </head>
  <body>
    {% block body %}
    {% endblock body %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha2/dist/js/bootstrap.bundle.min.js" integrity="sha384-qKXV1j0HvMUeCBQ+QVp7JcfGl760yU08IQ+GpUo5hlbpg51QRiuqHAJz8+BrxE/N" crossorigin="anonymous"></script>
    <script>
      {% block script %}
      {% endblock script %}
    </script>
  </body>
</html>

Django_01/accountbooks/templates/accountbooks/detail.html
{% extends 'accountbooks/base.html' %}

{% block body %}
<div class="container mt-5 text-center">
  <div class="card m-auto" style="width: 24rem;">
    <div class="card-body">
      <h3 class="card-titile mb-2">{{ accountbook.note }}</h3>
      <table class="table">
        <tbody>
          <tr>
            <th scope="row" class="text-start">메모</th>
            <td class="text-end">{{ accountbook.description }}</td>
          </tr>
          <tr>
            <th scope="row" class="text-start">분류</th>
            <td class="text-end">{{ accountbook.category }}</td>
          </tr>
          <tr>
            <th scope="row" class="text-start">사용 금액</th>
            <td class="text-end">{{ accountbook.amount }}</td>
          </tr>
          <tr>
            <th scope="row" class="text-start">사용 날짜</th>
            <td class="text-end">{{ accountbook.date }}</td>
          </tr>
          <tr>
            <th scope="row" class="text-start">생성 날짜</th>
            <td class="text-end">{{ accountbook.created_at|date:"Y-m-d D H:i:s" }}</td>
          </tr>
          <tr>
            <th scope="row" class="text-start">수정 날짜</th>
            <td class="text-end">{{ accountbook.updated_at|date:"Y-m-d D H:i:s" }}</td>
          </tr>
        </tbody>
      </table>
      <div class="d-flex justify-content-between">
        <a class="btn btn-outline-secondary" href="{% url 'accountbooks:index' %}">뒤로가기</a>
        <div>
          <a class="btn btn-outline-primary" href="{% url 'accountbooks:edit' accountbook.pk %}">수정</a>
          <a class="btn btn-outline-info" href="{% url 'accountbooks:copy' accountbook.pk %}">복사</a>
          <a class="btn btn-outline-danger" href="{% url 'accountbooks:delete' accountbook.pk %}">삭제</a>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock body %}

Django_01/accountbooks/templates/accountbooks/edit.html
{% extends 'accountbooks/base.html' %}

{% block style %}
.form-floating>.form-control,
.form-floating>.form-control-plaintext {
  padding: 0rem 0.75rem;
}

.form-floating>.form-control,
.form-floating>.form-control-plaintext,
.form-floating>.form-select {
  height: calc(3.5rem + 8px);
  line-height: 2;
}

.form-floating>label {
  padding: 1rem 0.75rem;
}
{% endblock style %}

{% block body %}
<div class="container mt-5">
  <div class="card w-25 m-auto">
    <form action="{% url 'accountbooks:create' %}" method="POST" class="needs-validation card-body" novalidate>
      {% csrf_token %}
      <div class="form-floating mb-3">
        <input type="text" class="form-control" id="note" name="note" placeholder="내용" required value="{{ accountbook.note }}">
        <div class="invalid-feedback text-start">내용을 입력하세요</div>
        <label for="note">내용</label>
      </div>
      <div class="form-floating mb-3">
        <textarea class="form-control" placeholder="메모" id="description" name="description" style="height: 10rem;">{{ accountbook.description }}</textarea>
        <label for="description">메모</label>
      </div>
      <div class="form-floating mb-3">
        <select class="form-select" id="category" name="category">
          <option value="식비" {% if accountbook.category == '식비' %}selected{% endif %}>식비</option>
          <option value="품위유지비" {% if accountbook.category == '품위유지비' %}selected{% endif %}>품위유지비</option>
          <option value="저축" {% if accountbook.category == '저축' %}selected{% endif %}>저축</option>
          <option value="주거비" {% if accountbook.category == '주거비' %}selected{% endif %}>주거비</option>
          <option value="교통비" {% if accountbook.category == '교통비' %}selected{% endif %}>교통비</option>
          <option value="문화생활비" {% if accountbook.category == '문화생활비' %}selected{% endif %}>문화생활비</option>
        </select>
        <label for="category">분류</label>
      </div>
      <div class="form-floating mb-3">
        <input type="number" class="form-control" id="amount" name="amount" value="{{ accountbook.amount }}" min="0">
        <label for="amount">사용 금액</label>
      </div>
      <div class="form-floating mb-3">
        <input type="date" class="form-control" id="date" name="date" value="{{ accountbook.date|date:"Y-m-d" }}">
        <label for="date">사용 날짜</label>
      </div>
      <div class="d-flex justify-content-between">
        <a class="btn btn-outline-danger" href="{% url 'accountbooks:detail' accountbook.pk %}">뒤로가기</a>
        <input class="btn btn-outline-primary" type="submit" value="수정완료">
      </div>
    </form>
  </div>
</div>
{% endblock body %}

{% block script %}
(() => {
  'use strict'

  // Fetch all the forms we want to apply custom Bootstrap validation styles to
  const forms = document.querySelectorAll('.needs-validation')

  // Loop over them and prevent submission
  Array.from(forms).forEach(form => {
    form.addEventListener('submit', event => {
      if (!form.checkValidity()) {
        event.preventDefault()
        event.stopPropagation()
      }

      form.classList.add('was-validated')
    }, false)
  })
})()
{% endblock script %}

Django_01/accountbooks/templates/accountbooks/index.html
{% extends 'accountbooks/base.html' %}

{% block style %}
@font-face {
  font-family: 'GmarketSans';
  font-weight: 500;
  font-style: normal;
  src: url('https://cdn.jsdelivr.net/gh/webfontworld/gmarket/GmarketSansMedium.eot');
  src: url('https://cdn.jsdelivr.net/gh/webfontworld/gmarket/GmarketSansMedium.eot?#iefix') format('embedded-opentype'),
       url('https://cdn.jsdelivr.net/gh/webfontworld/gmarket/GmarketSansMedium.woff2') format('woff2'),
       url('https://cdn.jsdelivr.net/gh/webfontworld/gmarket/GmarketSansMedium.woff') format('woff'),
       url('https://cdn.jsdelivr.net/gh/webfontworld/gmarket/GmarketSansMedium.ttf') format("truetype");
  font-display: swap;
} 

h1 {
  font-family: 'GmarketSans';
}
{% endblock style %}

{% block body %}
<div class="container mt-5 text-center" style="width: 80%;">
  <h1 class="mb-5">Account Book</h1>
  <div class = "d-flex justify-content-end mb-2">
    <button class="btn btn-outline-dark btn-sm me-2" id="all" value="전체" data-filter="전체">전체</button>
    <button class="btn btn-outline-dark btn-sm me-2" id="eat" value="식비" data-filter="식비">식비</button>
    <button class="btn btn-outline-dark btn-sm me-2" id="looks" value="품위유지비" data-filter="품위유지비">품위유지비</button>
    <button class="btn btn-outline-dark btn-sm me-2" id="deposit" value="저축" data-filter="저축">저축</button>
    <button class="btn btn-outline-dark btn-sm me-2" id="live" value="주거비" data-filter="주거비">주거비</button>
    <button class="btn btn-outline-dark btn-sm me-2" id="trans" value="교통비" data-filter="교통비">교통비</button>
    <button class="btn btn-outline-dark btn-sm me-2" id="culture" value="문화생활비" data-filter="문화생활비">문화생활비</button>
  </div>
  <table class="table table-hover m-auto mb-2">
    <thead>
      <tr class="table-dark">
        <th scope="col" onclick="sortData(0)" style="cursor: pointer; ">내용</th>
        <th scope="col" onclick="sortData(1)" style="cursor: pointer; width: 20%;">분류</th>
        <th scope="col" onclick="sortData(2)" style="cursor: pointer; width: 20%;">사용 금액</th>
        <th scope="col" onclick="sortData(3)" style="cursor: pointer; width: 20%;">사용 날짜</th>
      </tr> 
    </thead>
    <tbody>
      {% for accountbook in accountbooks %}
        <tr>
          <th scope="row" class="text-truncate data" onclick="location.href='{% url 'accountbooks:detail' accountbook.pk %}'" style="cursor:pointer;" data-type="{{ accountbook.category }}">{{ accountbook.note }}</th>
          <td class="data {{ accountbook.category }}" data-type="{{ accountbook.category }}">{{ accountbook.category }}</td>
          <td class="data" data-type="{{ accountbook.category }}">{{ accountbook.amount|floatformat:"g" }}</td>
          <td class="data" data-type="{{ accountbook.category }}">{{ accountbook.date|date:"Y.m.d D" }}</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
  <div class="text-end">
    <a class="btn btn-outline-dark" href="{% url 'accountbooks:new' %}">사용내역 추가</a>
  </div>
</div>
{% endblock body %}

{% block script %}
const btn = document.querySelectorAll(".btn-sm")
const data = document.querySelectorAll(".data")

btn.forEach(b=>b.addEventListener("click", (e) => {
  const filter = e.target.dataset.filter;

  if (filter == null) {
    return;
  }

  data.forEach((row) => {
    if (filter === "전체" || filter === row.dataset.type) {
      row.style.removeProperty('display')
    } else {
      row.style.display = "none"
    }
  })
}))

function sortData(n) {
  let table = document.querySelector(".table")
  let rows, i, x, y, count = 0
  let switching = true
  let Switch = false
  let direction = "ascending"

  while (switching) {
    switching = false
    let rows = table.rows

    for (i = 1; i < (rows.length - 1); i++) {
      Switch = false

      x = rows[i].querySelectorAll(".data")[n]
      y = rows[i + 1].querySelectorAll(".data")[n]

      if (direction == "ascending") {
        if (x.innerHTML.toLowerCase() > y.innerHTML.toLowerCase()) {
          Switch = true
          break
        }
      } else if (direction == "descending") {
        if (x.innerHTML.toLowerCase() < y.innerHTML.toLowerCase()) {
          Switch = true
          break
        }
      }
    }
    if (Switch) {
      rows[i].parentNode.insertBefore(rows[i + 1], rows[i]);
      switching = true
      count++;
    } else {
      if (count == 0 && direction == "ascending") {
        direction = "descending"
        switching = true
      }
    }
  }
}
{% endblock script %}

Django_01/accountbooks/templates/accountbooks/new.html
{% extends 'accountbooks/base.html' %}

{% block style %}
.form-floating>.form-control,
.form-floating>.form-control-plaintext {
  padding: 0rem 0.75rem;
}

.form-floating>.form-control,
.form-floating>.form-control-plaintext,
.form-floating>.form-select {
  height: calc(3.5rem + 8px);
  line-height: 2;
}

.form-floating>label {
  padding: 1rem 0.75rem;
}
{% endblock style %}

{% block body %}
<div class="container mt-5">
  <div class="card w-25 m-auto">
    <form action="{% url 'accountbooks:create' %}" method="POST" class="needs-validation card-body" novalidate>
      {% csrf_token %}
      <div class="form-floating mb-3">
        <input type="text" class="form-control" id="note" name="note" placeholder="내용" required>
        <div class="invalid-feedback text-start">내용을 입력하세요</div>
        <label for="note">내용</label>
      </div>
      <div class="form-floating mb-3">
        <textarea class="form-control" placeholder="메모" id="description" name="description" style="height: 10rem;"></textarea>
        <label for="description">메모</label>
      </div>
      <div class="form-floating mb-3">
        <select class="form-select" id="category" name="category">
          <option value="식비">식비</option>
          <option value="품위유지비">품위유지비</option>
          <option value="저축">저축</option>
          <option value="주거비">주거비</option>
          <option value="교통비">교통비</option>
          <option value="문화생활비">문화생활비</option>
        </select>
        <label for="category">분류</label>
      </div>
      <div class="form-floating mb-3">
        <input type="number" class="form-control" id="amount" name="amount" value="0" min="0">
        <label for="amount">사용 금액</label>
      </div>
      <div class="form-floating mb-3">
        <input type="date" class="form-control" id="date" name="date">
        <label for="date">사용 날짜</label>
      </div>
      <div class="d-flex justify-content-between">
        <a class="btn btn-outline-danger" href="{% url 'accountbooks:index' %}">뒤로가기</a>
        <input class="btn btn-outline-primary" type="submit" value="추가하기">
      </div>
    </form>
  </div>
</div>
{% endblock body %}

{% block script %}
(() => {
  'use strict'

  // Fetch all the forms we want to apply custom Bootstrap validation styles to
  const forms = document.querySelectorAll('.needs-validation')

  // Loop over them and prevent submission
  Array.from(forms).forEach(form => {
    form.addEventListener('submit', event => {
      if (!form.checkValidity()) {
        event.preventDefault()
        event.stopPropagation()
      }

      form.classList.add('was-validated')
    }, false)
  })
})()

document.getElementById("date").value = new Date().toISOString().substring(0, 10)
{% endblock script %}