Django_02/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('signup/', views.signup, name='signup'),
    path('delete/', views.delete, name='delete'),
    path('update/', views.update, name='update'),
    path('password/', views.password, name='password')
]

Django_02/posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'
urlpatterns = [
    path('', views.index, name='index'),
    path('category/<str:subject>/', views.category, name='category'),
    path('create/', views.create, name='create'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/update/', views.update, name='update'),
]

Django_02/project_two/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('posts/', include('posts.urls')),
]

Django_02/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>
      {% block title %}{% endblock title %}
    </title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <style>
      @import url("https://cdn.jsdelivr.net/gh/orioncactus/pretendard@v1.3.6/dist/web/variable/pretendardvariable.css");

      @font-face {
        font-family: 'GmarketSansMedium';
        src: url('https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_2001@1.1/GmarketSansMedium.woff') format('woff');
        font-weight: normal;
        font-style: normal;
      }

      * { font-family: 'Pretendard Variable'; }

      a {
        text-decoration-line: none;
        color: inherit;
      }

      .side {
        line-height: 1.8;
        font-size: 1.5rem;
      }

      .errorlist {
        list-style: none;
        margin: 0;
        padding: 0;
      }
      {% block style %}{% endblock style %}
    </style>
  </head>
  <body>
    <div class="d-flex flex-column">
      <nav class="navbar navbar-expand sticky-top z-index-3 bg-white border-bottom" style="width: 100%; background-color: #e3f2fd;">
        <div class="container d-flex justify-content-between">
          <a class="navbar-brand ms-3 fs-1" href="{% url 'posts:index' %}">POST</a>
          <div>
            <ul class="navbar-nav">
              {% if request.user.is_authenticated %}
              <li class="nav-item me-3" style="line-height: 2.5;">
                <span onclick="location.href='{% url 'accounts:update' %}'" style="cursor: pointer;"><b>{{ user }}</b>님</span> 안녕하세요
              </li>
              <li class="nav-item">
                <form action="{% url 'accounts:logout' %}" method="POST" style="font-family: 'GmarketSansMedium';">
                  {% csrf_token %}
                  <button type="sumbit" class="btn btn-outline-danger">로그아웃</button>
                </form>
              </li>
              {% else %}
              <li class="nav-item">
                <a href="{% url 'accounts:signup' %}" class="btn btn-outline-danger nav-link me-3">회원가입</a>
              </li>
              <li class="nav-item">
                <a href="{% url 'accounts:login' %}" class="btn btn-outline-primary nav-link">로그인</a>
              </li>
              {% endif %}
            </ul>
          </div>
        </div>
      </nav>
      <div class="d-flex">
        <aside class="d-flex flex-column flex-shrink-0 p-3 text-center" style="width: 16rem;">
          <h4>IT 정보 공유</h3>
          <hr class="mt-0">
          {% if request.user.is_authenticated %}
            <a href="{% url 'posts:create' %}" class="link-danger side">게시글 작성</a>
          {% endif %}
          <a class="side" href="{% url 'posts:index' %}">전체 글 보기</a>
          <a class="side" href="{% url 'posts:category' '개발' %}">개발</a>
          <a class="side" href="{% url 'posts:category' 'CS' %}">CS</a>
          <a class="side" href="{% url 'posts:category' '신기술' %}">신기술</a>
        </aside>
        <div class="flex-grow-1 mt-3">
          {% block body %}{% endblock body %}
        </div>
      </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
    <script>
      {% block script %}{% endblock script %}
    </script>
  </body>
</html>

Django_02/templates/error.html
{% if form.errors %}
<div class="alert alert-danger">
  {% for field in form %}
  {% if field.errors %}
  <div class="pt-1">
    <strong>{{ field.label }}</strong>
    {{ field.errors }}
  </div>
  {% endif %}
  {% endfor %}
  {% for error in form.non_field_errors %}
  <div>
    <strong>{{ error }}</strong>
  </div>
  {% endfor %}
</div>
{% endif %}