Django_02/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('signup/', views.signup, name='signup'),
    path('delete/', views.delete, name='delete'),
    path('update/', views.update, name='update'),
    path('password/', views.password, name='password')
]

Django_02/posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'
urlpatterns = [
    path('', views.index, name='index'),
    path('category/<str:subject>/', views.category, name='category'),
    path('create/', views.create, name='create'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/update/', views.update, name='update'),
]

Django_02/project_two/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('posts/', include('posts.urls')),
]

Django_02/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    birthday = models.DateField(null=True, blank=True)

Django_02/accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserChangeForm, UserCreationForm
from django.contrib.auth import get_user_model
import datetime


years = [x for x in range(1940, datetime.datetime.now().year + 1)]

class CustomUserCreationForm(UserCreationForm):
    username = forms.CharField(
        label='아이디',
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'placeholder': '아이디를 입력하세요',
            }
        ),
    )
    email = forms.EmailField(
        label='이메일',
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'placeholder': '이메일을 입력하세요',
            }
        ),
    )
    first_name = forms.CharField(
        label='이름',
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'placeholder': '이름을 입력하세요',
            }
        ),
    )
    last_name = forms.CharField(
        label='성',
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'placeholder': '성을 입력하세요',
            }
        ),
    )
    birthday = forms.DateField(
        initial=datetime.date(2000, 1, 1),
        label='생년월일',
        widget=forms.DateInput(
            attrs={
                'type':'date',
                'class': 'form-control',
                'placeholder': '생년월일'
            }
        ),
    )
    password1 = forms.CharField(
        label='비밀번호',
        widget=forms.PasswordInput(
            attrs={
                'class': 'form-control',
                'placeholder': '비밀번호를 입력하세요',
            }
        ),
    )
    password2 = forms.CharField(
        label='비밀번호 확인',
        widget=forms.PasswordInput(
            attrs={
                'class': 'form-control',
                'placeholder': '비밀번호를 다시 입력하세요',
            }
        ),
    )
    
    class Meta(UserCreationForm.Meta):
        model = get_user_model()
        fields = ('username', 'email', 'first_name', 'last_name', 'password1', 'password2', 'birthday')


class CustomUserChangeForm(UserChangeForm):
    email = forms.EmailField(
        label='이메일',
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'placeholder': '이메일을 입력하세요',
            }
        )
    )
    first_name = forms.CharField(
        label='이름',
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'placeholder': '이름을 입력하세요'
            }
        )
    )
    last_name = forms.CharField(
        label='성',
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'placeholder': '성을 입력하세요'
            }
        )
    )

    class Meta(UserChangeForm.Meta):
        model = get_user_model()
        fields = ('email', 'first_name', 'last_name',)

Django_02/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import AuthenticationForm, PasswordChangeForm
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from .forms import CustomUserChangeForm, CustomUserCreationForm


def login(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
           auth_login(request, form.get_user())
           return redirect('posts:index')
    else:
      form = AuthenticationForm()
    context = {
       'form': form,
    }
    return render(request, 'accounts/login.html', context)


@login_required
def logout(request):
   auth_logout(request)
   return redirect('posts:index')


def signup(request):
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
           user = form.save()
           auth_login(request, user)
           return redirect('posts:index')
    else:
        form = CustomUserCreationForm()
    context = {
      'form': form,
    }
    return render(request, 'accounts/signup.html', context)


@login_required
def delete(request):
   request.user.delete()
   auth_logout(request)
   return redirect('posts:index')


@login_required
def update(request):
    if request.method == 'POST':
      form = CustomUserChangeForm(request.POST, instance=request.user)
      if form.is_valid():
        user = form.save()
        update_session_auth_hash(request, user)
        return redirect('posts:index')
    else:
        form = CustomUserChangeForm(instance=request.user)
    context = {
       'form': form,
    }
    return render(request, 'accounts/update.html', context)


@login_required
def password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)
            return redirect('posts:index')
    else:
        form = PasswordChangeForm(request.user)
    context = {
        'form': form,
    }
    return render(request, 'accounts/password.html', context)

Django_02/accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% block title %} 로그인 {% endblock title %}
{% block style %}
.form-floating>.form-control,
.form-floating>.form-control-plaintext {
  padding: 0rem 0.75rem;
}

.form-floating>.form-control,
.form-floating>.form-control-plaintext,
.form-floating>.form-select {
  height: calc(3.5rem + 8px);
  line-height: 2;
}

.form-floating>label {
  padding: 1rem 0.75rem;
}
{% endblock style %}
{% block body %}
<div class="container" style="width: 40%;">
  <h2 class="my-3 text-center">로그인</h2>
  <form action="{% url 'accounts:login' %}" method='POST'>
    {% csrf_token %}
    {% include 'error.html' %}
    <div class="form-floating mb-3">
      {{ form.username }}
      <label for="{{ form.username.id_for_label }}">아이디</label>
    </div>
    <div class="form-floating mb-3">
      {{ form.password }}
      <label for="{{ form.password.id_for_label }}">비밀번호</label>
    </div>
    <div class="d-flex justify-content-between">
      <a href="{% url 'posts:index' %}" class="btn btn-outline-danger">뒤로가기</a>
      <div>
        <a href="{% url 'accounts:signup' %}" class="btn btn-outline-success me-1">회원가입</a>
        <input type="submit" value="로그인" class="btn btn-outline-primary">
      </div>
    </div>
  </form>
</div>
{% endblock body %}
{% block script %}
const username = document.querySelector("#{{ form.username.id_for_label }}")
const password = document.querySelector("#{{ form.password.id_for_label }}")
username.classList.add("form-control")
password.classList.add("form-control")
username.placeholder = '아이디를 입력하세요'
password.placeholder = '비밀번호를 입력하세요'
{% endblock script %}

Django_02/accounts/templates/accounts/password.html
{% extends 'base.html' %}
{% block title %}비밀번호 변경{% endblock title %}
{% block style %}
.form-floating>.form-control,
.form-floating>.form-control-plaintext {
  padding: 0rem 0.75rem;
}

.form-floating>.form-control,
.form-floating>.form-control-plaintext,
.form-floating>.form-select {
  height: calc(3.5rem + 8px);
  line-height: 2;
}

.form-floating>label {
  padding: 1rem 0.75rem;
}
{% endblock style %}
{% block body %}
<div class="container mt-5 w-50 m-auto">
  <h1 class="text-center">비밀번호 변경</h1>
  <div class="mt-3 m-auto text-center">
    <div class="card-body">
      <form action="{% url 'accounts:password' %}" method="POST">
        {% csrf_token %}
        {% include 'error.html' %}
        <div class="form-floating mb-3">
          {{ form.old_password }}
          <label for="{{ form.old_password.id_for_label }}">기존 비밀번호</label>
        </div>
        <div class="form-floating mb-3">
          {{ form.new_password1 }}
          <label for="{{ form.new_password1.id_for_label }}">새 비밀번호</label>
        </div>
        <div class="form-floating mb-3">
          {{ form.new_password2 }}
          <label for="{{ form.new_password2.id_for_label }}">새 비밀번호 확인</label>
        </div>
        <p class="text-start">
          다른 개인 정보와 유사한 비밀번호는 사용할 수 없습니다.<br>
          비밀번호는 최소 8자 이상이어야 합니다.<br>
          통상적으로 자주 사용되는 비밀번호는 사용할 수 없습니다.<br>
          숫자로만 이루어진 비밀번호는 사용할 수 없습니다.
        </p>
        <div class="d-flex justify-content-between mt-2">
          <a href="{% url 'posts:index' %}" class="btn btn-outline-danger">뒤로가기</a>
          <input type="submit" class="btn btn-outline-primary" value="변경">
        </div>
      </form>
    </div>
  </div>
</div>
{% endblock body %}
{% block script %}
const oldPw = document.querySelector("#{{ form.old_password.id_for_label }}")
const newPw1 = document.querySelector("#{{ form.new_password1.id_for_label }}")
const newPw2 = document.querySelector("#{{ form.new_password2.id_for_label }}")
oldPw.classList.add("form-control")
newPw1.classList.add("form-control")
newPw2.classList.add("form-control")
oldPw.placeholder = '기존 비밀번호를 입력하세요'
newPw1.placeholder = '새로운 비밀번호를 입력하세요'
newPw2.placeholder = '새로운 비밀번호를 다시 입력하세요'
{% endblock script %}

Django_02/accounts/templates/accounts/signup.html
{% extends 'base.html' %}
{% block title %} 회원가입 {% endblock title %}
{% block body %}
<div class="container m-auto" style="width: 40%;">
  <h1 class="text-center mb-3">회원가입</h1>
  <form action="{% url 'accounts:signup' %}" method="POST">
    {% csrf_token %}
    {% include 'error.html' %}
    <div class="form-floating mb-3">
      {{ form.username }}
      <label for="{{ form.username.id_for_label }}">아이디</label>
      <p class="mt-1 text-secondary">150자 이하의 문자, 숫자 그리고 @.+-_만 가능합니다.</p>
    </div>
    <div class="form-floating mb-3">
      {{ form.email }}
      <label for="{{ form.email.id_for_label }}">이메일</label>
    </div>
    <div class="d-flex justify-content-between">
      <div class="form-floating mb-3 col-6">
        {{ form.last_name }}
        <label for="{{ form.last_name.id_for_label }}">성</label>
      </div>
      <div class="form-floating mb-3 col-6">
        {{ form.first_name }}
        <label for="{{ form.first_name.id_for_label }}">이름</label>
      </div>
    </div>
    <div class="form-floating mb-3">
      {{ form.birthday }}
      <label for="{{ form.birthday.id_for_label|date:"Y-m-d" }}">생년월일</label>
    </div>
    <div class="form-floating mb-3">
      {{ form.password1 }}
      <label for="{{ form.password1.id_for_label }}">비밀번호</label>
    </div>
    <div class="form-floating mb-3">
      {{ form.password2 }}
      <label for="{{ form.password2.id_for_label }}">비밀번호 확인</label>
    </div>
    <p class="text-secondary">
      다른 개인 정보와 유사한 비밀번호는 사용할 수 없습니다.<br>
      비밀번호는 최소 8자 이상이어야 합니다.<br>
      통상적으로 자주 사용되는 비밀번호는 사용할 수 없습니다.<br>
      숫자로만 이루어진 비밀번호는 사용할 수 없습니다.
    </p>
    <div class="d-flex justify-content-between">
      <a href="{% url 'posts:index' %}" class="btn btn-outline-danger">뒤로가기</a>
      <input type="submit" value="가입" class="btn btn-outline-primary">
    </div>
  </form>
</div>
{% endblock body %}

Django_02/accounts/templates/accounts/update.html
{% extends 'base.html' %}
{% block title %} 회원정보 수정 {% endblock title %}
{% block style %}
.form-floating>.form-control,
.form-floating>.form-control-plaintext {
  padding: 0rem 0.75rem;
}

.form-floating>.form-control,
.form-floating>.form-control-plaintext,
.form-floating>.form-select {
  height: calc(3.5rem + 8px);
  line-height: 2;
}

.form-floating>label {
  padding: 1rem 0.75rem;
}
{% endblock style %}
{% block body %}
<div class="container" style="width: 40%;">
  <h1 class="text-center mb-3">회원정보 수정</h1>
  <div class="mb-3">
    <form action="{% url 'accounts:delete' %}" method="POST" class="d-flex justify-content-between">
      {% csrf_token %}
      <a href="{% url 'posts:index' %}" class="btn btn-outline-danger btn-sm">뒤로가기</a>
      <input type="submit" class="btn btn-warning btn-sm" value="탈퇴">
    </form>
  </div>
  <form action="{% url 'accounts:update' %}" method="POST">
    {% csrf_token %}
    {% include 'error.html' %}
    <div class="form-floating mb-3">
      {{ form.email }}
      <label for="{{ form.email.id_for_label }}">이메일</label>
    </div>
    <div class="d-flex">
      <div class="form-floating mb-3 col-6">
        {{ form.last_name }}
        <label for="{{ form.last_name.id_for_label }}">성</label>
      </div>
      <div class="form-floating mb-3 col-6">
        {{ form.first_name }}
        <label for="{{ form.first_name.id_for_label }}">이름</label>
      </div>
    </div>
    <div class="text-end">
      <a href="{% url 'accounts:password' %}" class="btn btn-outline-danger me-1">비밀번호 변경</a>
      <input type="submit" value="수정" class="btn btn-outline-primary">
    </div>
  </form>
</div>
{% endblock body %}